### ISSUE TITLE
Additional file extensions

### ISSUE THREAD

**Issue by ybiquitous** [rubocop-hq/rubocop-md#8]
Hello, `rubocop-md` currently supports `.md` and `.markdown` extensions,

https://github.com/rubocop-hq/rubocop-md/blob/38addb370ca65283ce9d8d9770d6fe6ce64c65b7/lib/rubocop/markdown/rubocop_ext.rb#L5

also, what about adding the support of the following extensions according to `linguist`?

https://github.com/github/linguist/blob/96ca71ab99c2f9928d5d69f4c08fd2a51440d045/lib/linguist/languages.yml#L3065-L3083

- .mdown
- .mdwn
- .mdx
- .mkd
- .mkdn
- .mkdown
- .ronn
- .workbook

**Comment by palkan** [comment]
Great suggestion!

Would you like to propose a PR?

**Comment by ybiquitous** [comment]
Yes! I'll do it soon. 👍
